### ISSUE TITLE
Write workshop presentation script and plan

### ISSUE THREAD

**Issue by bachnguyenTE** [aisutd/Intro-to-NLP-pretrained#2]
**Complete the workshop presentation script.**

**Requirements**
- The workshop content script follows the proposed presentation structure in the [project plan](https://docs.google.com/document/d/151ZJmJo5EUPPUXXdfP02gBdGqZXSm_tt4cWrCbHsmaU/edit?usp=sharing).
- The workshop content is of good quality; that is, easily _presentable_ and _comprehensible_ for the audience. 

**To-dos**
To-dos based on parts of the workshop presentation. 
- [X] Workshop Introduction/Overview
- [x] Theoretical Introduction to Vector Representations and Embedding
- [x] Theory of Embedding Algorithms
- [x] Demonstrate and Visualize Word Embeddings
- [x] Conclusion of the Workshop
- [x] Material & Resources

**Progress**
Detailed workshop planning in progress: [[WPP] Introduction to NLP I: Embeddings and their applications](https://docs.google.com/document/d/1soVeWyEjeQNQRjrlQbUOKA8Is0p3cq0ha6_Yo8p0HPE/edit?usp=sharing)
