### ISSUE TITLE
Create workshop presentation slides

### ISSUE THREAD

**Issue by bachnguyenTE** [aisutd/Intro-to-NLP-pretrained#4]
**Complete the workshop presentation slides.**

**Requirements**
- The workshop slides structure follows/complement/expands content described in the workshop [presentation plan](https://docs.google.com/document/d/1soVeWyEjeQNQRjrlQbUOKA8Is0p3cq0ha6_Yo8p0HPE/edit?usp=sharing). 
- The workshop slides effectively _illustrate/visualize_ the abstract concepts presented by the plan. 
- The workshop slides are of good quality; that is, easily _presentable_ and _comprehensible_ for the audience.
- The choice of presentation slides format is up to the first contributor. 

**To-dos**
To-dos based on parts of the workshop presentation. 
- [x] Workshop Introduction/Overview
- [x] Theoretical Introduction to Vector Representations and Embedding
- [x] Theory of Embedding Algorithms
- [x] Demonstrate and Visualize Word Embeddings
- [x] Conclusion of the Workshop
